# Плейбук для установки postgres pro. Ставит на сервер с указанным для root паролем

---
- name: Установка postgres pro для Linux
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes


  pre_tasks:
    - name: Проверка, что система Linux
      fail:
        msg: "Этот плейбук предназначен только для Linux систем."
      when: ansible_os_family != "Debian" and ansible_os_family != "RedHat"

  roles:
    - linux/linux_postgres_1c
