# Простой шаблон по обновлению системы linux
# Если не нужен, можно убрать

---
- name: Установка обновлений для системы Linux
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes

  pre_tasks:
    - name: Проверка, что система Linux
      fail:
        msg: "Этот плейбук предназначен только для Linux систем."
      when: ansible_os_family != "Debian" and ansible_os_family != "RedHat"

  roles:
    - role: linux/linux_update
