# Пропинговка удаленного хоста Linux на успешный конект с Ansible
# Немного устарело, так как есть универсальный general_ping.yaml 

---
- name: Проверка связи с удаленным хостом
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes

  pre_tasks:
    - name: Проверка, что система Linux
      fail:
        msg: "Этот плейбук предназначен только для Linux систем."
      when: ansible_os_family != "Debian" and ansible_os_family != "RedHat"

  tasks:
    - name: Проверка доступности хоста
      ansible.builtin.ping:
