# Установка платформы 1с на linux сервер. Может использоваться 
# в том числе для обновления платформы на сервере

---
- name: Установка платформы 1с на сервер
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes

  pre_tasks:
    - name: Проверка, что система Linux
      fail:
        msg: "Этот плейбук предназначен только для Linux систем."
      when: ansible_os_family != "Debian" and ansible_os_family != "RedHat"

  roles:
    - linux/linux_platform_1c 
