# Плейбук для обновления 1с платформы на SQL сервере,
# включая проверки:
# свободное место, наличие старой версии, сравнение версий и тд

---
- name: Обновление платформы 1с на сервер
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
 
  roles:
    - linux/linux_platform_1c 
